export type courseInfoType={
    courseImageAddress: string,
    corseSubject: string,
    mentorImageAddress: string,
    mentorName: string,
    courseprice: string,
    numberOfLessons: number,
    aboutCourse:string
    language: string,
    numberOfStudent: number,
    lastUpdate: string,
    subtitle: string,
    level: string,
    access: string,
    subjectOne: string,
    subjectTowe: string,
    subjectThree: string,
    subjectFor: string,
    subjectFive: string,
    subjectSix: string,
    subjectSeven: string,
    subjectEight: string,
    subjectNine: string,
    lessonOneAddress: string,
    lessonToweAddress: string,
    lessonThreeAddress: string,
    lessonForAddress: string,
    lessonFiveAddress: string,
    lessonSixAddress: string,
    lessonSevenAddress: string,
    lessonEightAddress: string,
    lessonNineAddress: string,
    _id:string
  }